# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsmodel',
            name='recipe',
            field=models.ManyToManyField(to='cookbook.RecipesModel'),
        ),
    ]
