# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_ingredientsmodel_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsmodel',
            name='ingredient_nine',
            field=models.CharField(default='2018-06-15', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='ingredient_ten',
            field=models.CharField(default='2018-06-15', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='ingredinet_eight',
            field=models.CharField(default='2018-06-15', max_length=200),
            preserve_default=False,
        ),
    ]
