# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20180625_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_eight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_five',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_nine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_seven',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_six',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_ten',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
