# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20180625_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='recipe_creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
